// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>
using std::vector;
using namespace Rcpp;

// EqWages
vector<double> EqWages(vector <double> Others, vector<double> WagesInit);
RcppExport SEXP _Calibration_EqWages(SEXP OthersSEXP, SEXP WagesInitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vector <double> >::type Others(OthersSEXP);
    Rcpp::traits::input_parameter< vector<double> >::type WagesInit(WagesInitSEXP);
    rcpp_result_gen = Rcpp::wrap(EqWages(Others, WagesInit));
    return rcpp_result_gen;
END_RCPP
}
// EqWagesNumericVector
arma::vec EqWagesNumericVector(arma::vec Others, arma::vec WagesInit);
RcppExport SEXP _Calibration_EqWagesNumericVector(SEXP OthersSEXP, SEXP WagesInitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Others(OthersSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type WagesInit(WagesInitSEXP);
    rcpp_result_gen = Rcpp::wrap(EqWagesNumericVector(Others, WagesInit));
    return rcpp_result_gen;
END_RCPP
}
// DistanceEstimator
double DistanceEstimator(arma::vec Others, arma::vec WagesInit, arma::vec armaInitLWorkers, arma::vec armaInitProf);
RcppExport SEXP _Calibration_DistanceEstimator(SEXP OthersSEXP, SEXP WagesInitSEXP, SEXP armaInitLWorkersSEXP, SEXP armaInitProfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Others(OthersSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type WagesInit(WagesInitSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type armaInitLWorkers(armaInitLWorkersSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type armaInitProf(armaInitProfSEXP);
    rcpp_result_gen = Rcpp::wrap(DistanceEstimator(Others, WagesInit, armaInitLWorkers, armaInitProf));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Calibration_EqWages", (DL_FUNC) &_Calibration_EqWages, 2},
    {"_Calibration_EqWagesNumericVector", (DL_FUNC) &_Calibration_EqWagesNumericVector, 2},
    {"_Calibration_DistanceEstimator", (DL_FUNC) &_Calibration_DistanceEstimator, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_Calibration(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
