# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EqWages <- function(Others, WagesInit) {
    .Call(`_Calibration_EqWages`, Others, WagesInit)
}

EqWagesNumericVector <- function(Others, WagesInit) {
    .Call(`_Calibration_EqWagesNumericVector`, Others, WagesInit)
}

DistanceEstimator <- function(Others, WagesInit, armaInitLWorkers, armaInitProf) {
    .Call(`_Calibration_DistanceEstimator`, Others, WagesInit, armaInitLWorkers, armaInitProf)
}

